### ISSUE TITLE
Uninitialized string offset 1

### ISSUE THREAD

**Issue by youssefdegweyy** [Advaith3600/seamless-admin#4]
![Screenshot (30)](https://github.com/Advaith3600/seamless-admin/assets/32340496/90a98f83-e64c-430a-a82c-598d3f406358)

Just installed in a fresh new project laravel 10 latest version, tried with existing laravel 9 same error

**Comment by Advaith3600** [comment]
Hey, thank you for bringing this to my attention. Can you share your model with me for reproducing this issue?

**Comment by youssefdegweyy** [comment]
![Screenshot (31)](https://github.com/Advaith3600/seamless-admin/assets/32340496/b8422bf9-86e8-4b2b-99b6-5a0a2203edfc)

I only used it on this model but even before adding the trait to any of the models if I ran the seamless:clear command it gives the same error I don't know why

**Comment by Advaith3600** [comment]
The issue could lie in some other PHP file as well as the package analyse all files within the `Models` directory. Could you check if there is any non regular looking PHP files?

**Comment by youssefdegweyy** [comment]
it has an issue with the model "Cart" I don't exactly know why I will provide 2 screenshots 
![Screenshot (32)](https://github.com/Advaith3600/seamless-admin/assets/32340496/20243e46-4bd3-4791-9077-3d33e2b478e9)
![Screenshot (33)](https://github.com/Advaith3600/seamless-admin/assets/32340496/03a971ae-4dc1-4c24-9a35-c183253606c4)

**Comment by youssefdegweyy** [comment]
> it has an issue with the model "Cart" I don't exactly know why I will provide 2 screenshots ![Screenshot (32)](https://private-user-images.githubusercontent.com/32340496/310839525-20243e46-4bd3-4791-9077-3d33e2b478e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDY4NTEsIm5iZiI6MTcwOTgwNjU1MSwicGF0aCI6Ii8zMjM0MDQ5Ni8zMTA4Mzk1MjUtMjAyNDNlNDYtNGJkMy00NzkxLTkwNzctM2QzM2UyYjQ3OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwMTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZWRjZDc4ZmQyNjdmYjg0OTlkN2RmMmVkNDNhNmI3MjFlZjY4NTI5MDBmZWFhNTJiZWRhMTkwOTU0YTQ1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZNVaSQd-T_C3AoyDZhGxoT4KS2uMRlQk3M6u8Ixewg) ![Screenshot (33)](https://private-user-images.githubusercontent.com/32340496/310839546-03a971ae-4dc1-4c24-9a35-c183253606c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDY4NTEsIm5iZiI6MTcwOTgwNjU1MSwicGF0aCI6Ii8zMjM0MDQ5Ni8zMTA4Mzk1NDYtMDNhOTcxYWUtNGRjMS00YzI0LTlhMzUtYzE4MzI1MzYwNmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwMTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjRmZjQ2ODc2Y2M2MzAzNWM1ZmZhZjNmODEyZWYwNjlkZDMzY2YxYjFiNjFmNjc5ZDczZWNlZmVlNTFiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3QJmVB3FviI6MUNnJqlkQCZL7zwVYjHlFO6h-_ZxzAQ)

I deleted the Cart model it gave another error for Menu then for Offer then for PromoCode then for Reward then for UserFavorite when I deleted all these it ran successfully but they all gave the same error that I provided in the screenshot above from the console

**Comment by Advaith3600** [comment]
I have pushed a patch for this issue. Can you test it out using the `dev-main` version of the package?

update your composer.json
```json
{
    "advaith/seamless-admin": "dev-main",
}
```

and run `composer update advaith/seamless-admin` 

Let me know if you are still having the same issue or anything new
